export enum Specific {
    BBC = 'BBC',
    BEARDY = 'Beardy',
    BIGASS = 'Big Ass',
    BIGBALLS = 'Big Balls',
    BIGCOCK = 'Big Cock',
    EMO = 'Emo',
    GOTH = 'Goth',
    HAIRY = 'Hairy',
    HARIT_ARMPITS = 'Hairy armpits',
    MUSTACHE = 'Mustache',
    POV = 'POV',
    SHAVEN = 'Shaven',
    FEMBOY = 'Femboy',
    SISSY = 'Sissy',
    SMALL_COCK = 'Small Cock',
    TRIMMED = 'Trimmed',
    UNCUT = 'Uncut',
}
